name: build-binary

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Go mod tidy
      run: go mod tidy

    - name: Build fiat-crypto
      run: |
        docker build -t fiat-crypto:v0.0.9 ./bign/fiat/
        go install github.com/mmcloughlin/addchain/cmd/addchain@v0.4.0

    - name: Generate
      run: |
        cd ./bign/fiat/ && go run generate.go
        cd ./../ && go run generate.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bign-tar
        path: ./bign/
        retention-days: 7  # 将保留天数设置为 7 天 最多可设置90天

